name: UhcCore
main: com.gmail.val59000mc.UhcCore
version: 1.12.5 (dev_scenarios 1.2)
description: Automates UHC games on a dedicated server
author: val59000mc, Mezy
soft-depend: [WorldEdit,Vault]
api-version: 1.13
commands:
   uhccore:
        description: "Type '/uhccore help' to see a list of commands"
        usage: "/uhccore help (Debug command only!)"
        permission: "uhc-core.commands"
        permission-message: "You don't have the permission to use UHC-Core commands"
   chat:
        description: "Type '/chat' to toggle global chat"
        usage: "/chat"
        aliases: [c]
        permission-message: "You don't have the permission to use UHC-Core commands"
   teleport:
        description: "Type '/teleport <player>' to teleport to your teammates while spectating"
        usage: "/teleport <player>"
        permission-message: "You don't have the permission to use UHC-Core commands"
        aliases: [tp]
   start:
        description: "This command is used to toggle force starting of the game"
        usage: /<command>
        permission: "uhc-core.commands.start"
        permission-message: "You don't have the permission to use UHC-Core commands"
   scenarios:
        description: "This command is used to view and toggle scenarios."
        usage: /<command>
        aliases: [game, settings, uhc]
   teaminventory:
        description: "This command is used to open team inventory."
        usage: /<command>
        aliases: [ti, backpack, bp]